question_data = [
    {"text": "Assyrian king Sennacherib's destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.", "answer": "False"},
    {"text": "Time on Computers is measured via the EPOX System.", "answer": "False"},
    {"text": "The ADAM collecters in the Bioshock series are known as Little Sisters.", "answer": "True"},
    {"text": "FLAC stands for \"Free Lossless Audio Condenser\"", "answer": "False"},
    {"text": "Stevie Wonder's real name is Stevland Hardaway Morris.", "answer": "True"},
    {"text": "The Earth and the Moon roughly have the same mass.", "answer": "False"},
    {"text": "The man that shot Alexander Hamilton was named Aaron Burr.", "answer": "True"},
    {"text": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.", "answer": "True"},
    {"text": "Tony Hawk's extreme sports videogames revolve around performing professional BMX tricks.", "answer": "False"},
    {"text": "In \"Star Trek: The Next Generation\", Data is the only android in existence.", "answer": "False"},
    {"text": "The singer Billie Holiday was also known as \"Lady Day\".", "answer": "True"},
    {"text": "Rabbits can't vomit.", "answer": "True"},
    {"text": "The game \"Jetpack Joyride\" was created by \"Redbrick Studios\".", "answer": "False"},
    {"text": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.", "answer": "True"},
    {"text": "Ashley Frangipane performs under the stage name Halsey.", "answer": "True"},
    {"text": "The sum of all the numbers on a roulette wheel is 666.", "answer": "True"},
    {"text": "The game \"Battlefield 1\" takes place during World War I.", "answer": "True"},
    {"text": "In Portal, the Companion Cube's ARE sentient.", "answer": "True"},
    {"text": "Tokyo is the capital of Japan.", "answer": "True"},
    {"text": "Israel is 7 hours ahead of New York.", "answer": "True"},
    {"text": "EDM label Monstercat signs tracks instead of artists.", "answer": "True"},
    {"text": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.", "answer": "False"},
    {"text": "The music group Daft Punk got their name from a negative review they received.", "answer": "True"},
    {"text": "Water always boils at 100°C, 212°F, 373.15K, no matter where you are.", "answer": "False"},
    {"text": "American rapper Dr. Dre actually has a Ph.D. doctorate.", "answer": "False"},
    {"text": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.", "answer": "True"},
    {"text": "Coca-Cola's original colour was green.", "answer": "False"},
    {"text": "The Angry Video Game Nerd's alter ego is \"Board James\".", "answer": "True"},
    {"text": "The CEO of tech company Apple following Steve Jobs is named Tim Apple.", "answer": "False"},
    {"text": "The names of Tom Nook's cousins in the Animal Crossing franchise are named \"Timmy\" and \"Jimmy\".", "answer": "False"},
    {"text": "Michael Jackson had a pet python named 'Crusher'.", "answer": "True"},
    {"text": "A cancelled Call Of Duty title would have taken place in ancient Rome.", "answer": "True"},
    {"text": "In the game \"Racko\" you may pick up ANY card from the discard pile.", "answer": "False"},
    {"text": "A pasodoble is a type of Italian pasta sauce.", "answer": "False"},
    {"text": "Did Michael Jackson invent the moonwalk?", "answer": "False"},
    {"text": "The British organisation CAMRA stands for The Campaign for Real Ale.", "answer": "True"},
    {"text": "TF2: The Heavy's voice actor, Gary Schwartz, voices the Demoman as well", "answer": "True"},
    {"text": "Enthalpy is a measure of the energy that is not available for work during a thermodynamic process.", "answer": "False"},
    {"text": "The Ace Attorney trilogy was suppose to end with \"Phoenix Wright: Ace Attorney − Trials and Tribulations\" as its final game.", "answer": "True"},
    {"text": "There is an island in Japan called Ōkunoshima, A.K.A. \"Rabbit Island\", so named because of it's huge population of rabbits.", "answer": "True"},
    {"text": "Igneous rocks are formed by excessive heat and pressure.", "answer": "False"},
    {"text": "Sound can travel through a vacuum.", "answer": "False"},
    {"text": "The edutainment video game series character, Carmen Sandiego, is partially named after Brazilian actress, Carmen Miranda.", "answer": "True"},
    {"text": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.", "answer": "False"},
    {"text": "The United States Department of Homeland Security was formed in response to the September 11th attacks.", "answer": "True"},
    {"text": "One of Donald Trump's 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.", "answer": "True"},
    {"text": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.", "answer": "False"},
    {"text": "In Harry Potter and the Deathly Hallows, Hermione destroyed the fourth Horcrux by stabbing it with the Sword of Gryffindor.", "answer": "False"},
    {"text": "The word \"news\" originates from the first letters of the 4 main directions on a compass (North, East, West, South).", "answer": "False"},
]
